# Generated by Django 4.1.3 on 2022-11-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('responsable', models.CharField(max_length=50, verbose_name='Responsable')),
                ('estado', models.BooleanField()),
            ],
        ),
    ]
