# Generated by Django 4.1.3 on 2022-11-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0002_estado_alter_actividad_id_alter_actividad_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estado',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
