# Generated by Django 4.1.3 on 2022-11-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0003_alter_actividad_id_alter_estado_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
