# Generated by Django 4.1.3 on 2022-11-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0004_alter_actividad_id_alter_estado_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='estado',
        ),
        migrations.AlterField(
            model_name='actividad',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
